In [2]:
import numpy as np
import pandas as pd
import utils
import seaborn as sn
import matplotlib.pyplot as plt
from joblib import dump, load

In [3]:
data_big = pd.read_csv('data/big_results.csv', index_col=0)
data_big.head()

EXT1  EXT2  EXT3  EXT4  EXT5  EXT6  EXT7  EXT8  EXT9  EXT10  ...  _OPN9  \
0   4.0   1.0   5.0   2.0   5.0   1.0   5.0   2.0   4.0    1.0  ...    4.0   
1   3.0   5.0   3.0   4.0   3.0   3.0   2.0   5.0   1.0    5.0  ...    5.0   
2   2.0   3.0   4.0   4.0   3.0   2.0   1.0   3.0   2.0    5.0  ...    4.0   
3   2.0   2.0   2.0   3.0   4.0   2.0   2.0   4.0   1.0    4.0  ...    3.0   
4   3.0   3.0   3.0   3.0   5.0   3.0   3.0   5.0   3.0    4.0  ...    5.0   

   _OPN10   EXT   EST   AGR   CSN   OPN  MAX_SCORE  TYPE      CORR  
0     5.0  46.0  36.0  39.0  32.0  45.0       46.0     0  1.000000  
1     3.0  20.0  35.0  40.0  37.0  35.0       40.0     1  1.000000  
2     4.0  25.0  34.0  40.0  34.0  41.0       41.0     1  0.984049  
3     3.0  26.0  31.0  38.0  25.0  39.0       39.0    96  0.972907  
4     5.0  29.0  41.0  42.0  48.0  48.0       48.0     1  0.985012  

[5 rows x 108 columns]

In [4]:
best_class=data_big['TYPE'].value_counts()[:20].index.values.tolist()
best_class

[0, 1, 3, 4, 25, 7, 27, 14, 23, 20, 31, 5, 96, 179, 11, 16, 95, 40, 2, 10]

In [5]:
data_big_cleaned = data_big[data_big['TYPE'].isin(best_class)]
data_big_cleaned=data_big_cleaned.drop_duplicates()
data_big_cleaned

EXT1  EXT2  EXT3  EXT4  EXT5  EXT6  EXT7  EXT8  EXT9  EXT10  ...  \
0        4.0   1.0   5.0   2.0   5.0   1.0   5.0   2.0   4.0    1.0  ...   
1        3.0   5.0   3.0   4.0   3.0   3.0   2.0   5.0   1.0    5.0  ...   
2        2.0   3.0   4.0   4.0   3.0   2.0   1.0   3.0   2.0    5.0  ...   
3        2.0   2.0   2.0   3.0   4.0   2.0   2.0   4.0   1.0    4.0  ...   
4        3.0   3.0   3.0   3.0   5.0   3.0   3.0   5.0   3.0    4.0  ...   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...   
499994   3.0   1.0   4.0   3.0   2.0   1.0   3.0   4.0   4.0    4.0  ...   
499995   4.0   2.0   5.0   2.0   4.0   2.0   5.0   4.0   2.0    4.0  ...   
499996   2.0   2.0   4.0   5.0   4.0   1.0   1.0   1.0   5.0    5.0  ...   
499997   3.0   1.0   5.0   1.0   4.0   1.0   4.0   2.0   5.0    2.0  ...   
499998   3.0   4.0   3.0   2.0   4.0   2.0   1.0   2.0   4.0    5.0  ...   

        _OPN9  _OPN10   EXT   EST   AGR   CSN   OPN  MAX_SCORE  TYPE      CORR  
0         4.0     5.0  46.0  36.0  39.0  32.0  45.0       46.0     0  1.000000  
1         5.0     3.0  20.0  35.0  40.0  37.0  35.0       40.0     1  1.000000  
2         4.0     4.0  25.0  34.0  40.0  34.0  41.0       41.0     1  0.984049  
3         3.0     3.0  26.0  31.0  38.0  25.0  39.0       39.0    96  0.972907  
4         5.0     5.0  29.0  41.0  42.0  48.0  48.0       48.0     1  0.985012  
...       ...     ...   ...   ...   ...   ...   ...        ...   ...       ...  
499994    4.0     5.0  33.0  26.0  40.0  35.0  42.0       42.0     0  0.975817  
499995    5.0     4.0  36.0  34.0  41.0  24.0  42.0       42.0     0  0.983439  
499996    5.0     2.0  32.0  14.0  43.0  34.0  40.0       43.0     4  0.970462  
499997    5.0     5.0  44.0  24.0  40.0  45.0  49.0       49.0     4  0.984814  
499998    4.0     5.0  30.0  22.0  25.0  46.0  49.0       49.0    16  0.977913  

[432706 rows x 108 columns]

In [6]:
from sklearn_som.som import SOM
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from joblib import dump, load

In [7]:
X=data_big_cleaned.iloc[:,:50]
print(X)
Y=data_big_cleaned['TYPE']
print(Y)

        EXT1  EXT2  EXT3  EXT4  EXT5  EXT6  EXT7  EXT8  EXT9  EXT10  ...  \
0        4.0   1.0   5.0   2.0   5.0   1.0   5.0   2.0   4.0    1.0  ...   
1        3.0   5.0   3.0   4.0   3.0   3.0   2.0   5.0   1.0    5.0  ...   
2        2.0   3.0   4.0   4.0   3.0   2.0   1.0   3.0   2.0    5.0  ...   
3        2.0   2.0   2.0   3.0   4.0   2.0   2.0   4.0   1.0    4.0  ...   
4        3.0   3.0   3.0   3.0   5.0   3.0   3.0   5.0   3.0    4.0  ...   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...   
499994   3.0   1.0   4.0   3.0   2.0   1.0   3.0   4.0   4.0    4.0  ...   
499995   4.0   2.0   5.0   2.0   4.0   2.0   5.0   4.0   2.0    4.0  ...   
499996   2.0   2.0   4.0   5.0   4.0   1.0   1.0   1.0   5.0    5.0  ...   
499997   3.0   1.0   5.0   1.0   4.0   1.0   4.0   2.0   5.0    2.0  ...   
499998   3.0   4.0   3.0   2.0   4.0   2.0   1.0   2.0   4.0    5.0  ...   

        OPN1  OPN2  OPN3  OPN4  OPN5  OPN6  OPN7  OPN8  OPN9  OPN10  
0        5.0   1.

In [8]:
pd.Series(Y).value_counts()

0      143667
1      105328
3       30589
4       22700
25      14877
7       14634
27      14107
14      13665
23       9760
31       7874
20       7747
5        6874
96       6171
179      6066
11       5556
16       5447
95       4590
40       4554
2        4298
10       4202
Name: TYPE, dtype: int64

In [9]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [10]:
print(pd.Series(y_train).value_counts())

0      114968
1       84432
3       24561
4       18088
25      11874
7       11675
27      11285
14      10925
23       7789
31       6288
20       6212
5        5475
96       4897
179      4835
11       4456
16       4408
95       3632
40       3625
2        3404
10       3335
Name: TYPE, dtype: int64


In [11]:
som = load('som_big.joblib')
# som = SOM(m=5, n=4, dim=50, max_iter=1000000)
som.fit(x_train.to_numpy())
predictions = som.predict(x_test.to_numpy())

In [12]:
# dump(som, 'som_big.joblib') 

In [13]:
for i in range(len(predictions)):
    print(predictions[i], y_test.to_numpy()[i])

7 14
9 1
2 1
12 1
5 1
9 1
1 0
13 95
5 1
7 16
16 0
7 25
12 0
0 7
10 1
3 3
3 25
0 0
16 0
18 0
0 0
2 1
3 25
12 0
3 5
18 0
8 1
12 27
7 1
11 10
2 7
16 0
8 1
0 16
10 1
8 1
15 4
1 0
4 1
12 0
17 0
16 0
5 1
16 4
0 0
10 95
9 1
15 4
11 3
7 1
7 3
3 14
19 3
2 31
0 20
9 1
0 2
12 1
12 0
4 7
17 0
0 7
12 1
7 23
12 0
17 0
10 1
18 0
7 14
9 0
15 3
11 25
11 3
13 0
17 0
1 0
0 2
18 0
19 0
10 4
13 4
19 3
11 25
5 1
18 0
9 1
17 0
0 2
11 3
5 1
2 7
7 10
9 1
2 1
19 0
19 40
13 1
3 3
9 0
14 0
4 1
13 0
18 0
9 1
11 4
11 25
6 25
4 7
15 4
9 27
19 0
4 1
9 1
6 1
5 1
19 11
15 4
0 0
8 1
12 0
3 23
11 25
18 0
17 0
7 25
1 1
6 1
7 1
11 25
7 179
8 1
0 0
14 0
14 31
11 3
7 3
4 1
3 3
19 0
17 0
0 2
8 1
5 1
11 3
19 0
4 1
19 4
8 1
0 7
11 40
16 0
2 96
15 4
14 0
3 14
16 0
17 20
14 0
18 0
11 40
14 31
5 1
18 0
18 0
7 14
17 0
6 1
3 23
8 7
7 14
9 1
18 0
18 0
10 27
0 0
1 7
3 25
8 1
14 0
10 1
7 14
0 0
15 3
8 1
19 3
7 10
0 2
0 0
19 3
0 16
19 0
7 14
7 1
3 3
2 27
0 0
16 0
7 5
4 1
7 14
10 0
13 1
1 0
8 1
2 1
2 1
17 0
5 1
7 5
14 4
9 179
15 4
9 27
0

0 23
18 0
17 0
19 11
15 3
8 1
13 0
5 1
0 7
0 1
0 0
0 7
9 1
17 0
6 1
9 1
11 23
12 0
10 25
4 1
4 0
11 10
1 0
4 0
5 1
5 1
8 1
11 3
7 1
2 20
11 4
16 0
1 31
3 1
17 0
17 0
19 0
3 3
6 1
12 1
14 0
18 0
8 1
7 14
16 0
12 0
17 0
11 25
14 0
9 1
3 14
7 23
5 1
7 1
9 1
2 1
14 31
0 2
0 7
16 0
13 0
7 5
2 1
17 0
1 20
17 0
19 0
8 1
14 0
15 95
19 0
5 1
3 95
8 1
0 2
14 0
3 14
10 25
2 95
8 1
9 1
2 1
2 1
8 1
18 96
12 1
4 1
2 1
3 3
8 1
2 1
3 25
3 3
12 1
16 0
4 1
4 1
7 14
8 1
6 1
11 25
19 0
16 0
8 1
6 1
16 0
19 11
2 3
16 0
7 14
13 31
0 2
1 0
0 7
1 0
1 40
0 7
16 0
2 7
8 1
8 1
14 0
4 1
9 1
8 1
8 1
4 1
1 7
10 0
14 4
14 0
4 0
18 0
9 95
9 1
1 7
4 1
16 0
5 1
18 0
4 20
14 0
6 1
1 7
12 27
6 25
3 23
3 3
16 0
18 0
16 7
13 27
12 0
7 23
9 1
19 4
14 31
9 16
17 0
15 4
19 11
11 10
4 1
18 0
10 27
3 5
1 0
0 0
13 0
5 1
6 1
18 40
2 25
19 11
2 0
5 1
2 31
18 0
19 3
18 0
3 3
5 96
7 5
4 1
3 25
15 4
16 0
8 1
2 1
1 96
0 0
1 0
0 7
1 0
4 1
17 0
16 0
10 1
18 0
3 25
8 1
11 3
11 23
4 1
16 0
3 3
16 0
9 1
5 1
12 1
13 1
4 1
15 0
3 3
15 3
3 10

0 0
13 0
19 3
0 0
9 1
17 0
14 0
3 14
1 0
4 1
2 0
17 0
12 27
1 1
0 0
12 1
14 4
0 0
2 40
16 0
2 3
7 25
7 14
0 27
4 0
2 0
19 0
0 0
0 7
2 4
1 96
13 27
0 2
16 4
7 1
19 11
6 1
7 5
1 0
15 40
7 3
0 1
19 3
16 0
8 1
17 0
5 1
0 7
6 1
8 1
11 23
3 95
9 1
19 3
11 25
8 1
10 16
10 1
14 0
1 0
10 179
10 1
8 1
0 2
16 0
17 0
15 4
5 1
17 96
6 1
15 4
13 0
14 0
9 1
16 0
3 14
16 0
19 3
6 25
9 27
7 25
1 0
10 25
0 16
14 4
11 3
8 7
6 1
1 0
11 3
5 1
9 1
18 0
7 5
17 0
1 0
18 0
8 1
3 3
13 0
1 0
18 0
9 0
16 0
12 0
7 5
3 3
1 0
19 3
13 16
15 0
19 0
12 1
1 0
6 1
3 40
0 7
6 1
8 1
13 0
14 0
6 1
15 0
11 25
10 0
1 1
19 4
19 3
19 0
15 4
12 179
1 7
17 0
11 10
17 0
18 0
13 0
12 1
8 1
19 0
18 0
12 1
19 0
12 0
19 3
13 0
5 1
8 1
12 0
13 0
14 4
1 20
6 179
11 3
10 95
1 0
0 20
3 14
8 1
8 27
6 25
5 1
1 0
5 1
10 1
4 1
16 0
0 0
11 3
12 27
16 0
1 7
13 0
8 0
7 23
18 0
0 2
8 1
13 179
10 7
2 1
13 0
15 4
12 0
2 23
18 0
4 23
8 1
7 14
13 0
6 1
1 20
0 1
4 1
6 25
5 1
9 0
2 0
3 23
19 0
3 5
3 25
13 0
14 0
17 0
18 0
17 0
12 0
17 0
17 0
4 1
0 0
14

6 1
10 25
7 14
3 23
16 0
4 7
1 7
11 179
16 0
19 0
18 0
12 1
1 1
19 0
11 5
3 25
19 4
9 0
18 0
19 11
12 0
12 1
8 1
11 40
19 0
14 0
8 1
17 0
16 0
19 3
14 0
1 1
2 27
10 25
3 3
8 1
10 0
16 0
9 0
12 1
3 5
14 4
19 0
4 0
11 4
14 4
12 1
14 179
17 0
7 3
7 14
9 7
15 4
3 23
11 4
7 10
17 0
7 1
2 1
18 0
1 3
6 1
8 1
3 7
7 25
13 0
16 0
2 27
1 0
5 1
0 0
4 1
3 25
10 27
7 10
19 11
0 0
4 1
8 1
12 0
18 0
7 3
4 7
2 1
12 1
15 4
1 1
14 0
11 3
2 1
8 1
19 96
6 1
2 7
7 25
11 1
11 3
2 95
9 1
16 0
8 1
16 0
2 16
6 1
18 0
3 16
9 1
11 3
7 25
4 0
8 1
14 0
12 0
3 14
19 0
1 0
0 7
2 1
18 0
0 0
13 0
10 1
17 0
12 1
1 1
1 0
13 0
12 0
6 1
0 3
12 0
1 0
3 25
16 0
19 0
0 7
12 0
15 4
5 1
7 14
19 0
8 1
0 0
15 4
16 0
8 1
15 3
6 1
18 0
12 0
14 16
0 7
3 3
8 1
10 25
18 0
5 1
4 20
15 4
8 1
15 31
19 0
8 1
13 4
10 1
3 3
11 3
8 1
4 20
15 3
16 0
11 4
10 27
8 1
1 1
2 7
8 23
7 14
11 3
11 25
14 4
0 0
17 0
3 5
8 1
9 1
17 0
4 1
18 0
7 3
17 0
11 3
1 1
3 23
19 3
4 1
15 4
13 0
18 11
17 0
19 11
17 0
8 1
0 7
12 1
1 7
0 0
14 0
11 179
3 14
2 25
9 0
1

In [14]:
pd.Series(y_test).value_counts()

0      28699
1      20896
3       6028
4       4612
25      3003
7       2959
27      2822
14      2740
23      1971
31      1586
20      1535
5       1399
96      1274
179     1231
11      1100
16      1039
95       958
40       929
2        894
10       867
Name: TYPE, dtype: int64

In [15]:
pd.Series(predictions).value_counts()

0     5622
3     5501
19    5252
18    5051
17    5021
16    4982
8     4794
4     4495
15    4373
7     4337
14    4266
1     4209
11    4207
2     4016
12    3863
13    3700
10    3318
5     3219
9     3196
6     3120
dtype: int64

In [16]:
pred_classes=[]
for i in best_class:
    print(i)
    print(pd.Series(predictions)[list(pd.Series(y_test.tolist()).loc[lambda x : x == i].index)].value_counts())
    pred_classes.append(pd.Series(predictions)[list(pd.Series(y_test.tolist()).loc[lambda x : x == i].index)].value_counts().keys()[0])
    print('\n')
print(pred_classes)

0
17    4852
16    4547
18    4506
13    2476
14    2385
19    2037
0     1945
1     1813
12    1309
15     726
4      659
2      499
9      322
10     282
5      150
8      133
11      28
3       16
6       14
dtype: int64


1
8     4370
5     2736
4     2580
6     2312
9     1947
2     1732
12    1669
10    1053
1      898
7      638
11     298
3      270
0      170
13     108
16      62
14      41
18       7
15       5
dtype: int64


3
3     1319
19    1319
11    1313
15    1150
7      528
0      149
2       59
18      58
14      48
4       47
10      17
1       12
13       4
8        3
17       1
6        1
dtype: int64


4
15    1995
14     902
19     558
11     534
10     182
13     182
3      143
2       44
18      26
16      21
17      10
12       7
0        4
7        4
dtype: int64


25
3     694
7     640
11    585
10    487
6     476
2     106
9      13
8       2
dtype: int64


7
0     1424
1      353
2      340
4      331
12     127
8       97
3       79
9       62
16     

In [69]:
predictions_fix = predictions.copy()

In [70]:
for i in range(20):
    predictions_fix[predictions==pred_classes[i]]=best_class[i]

In [71]:
for i in best_class:
    print(i)
    print(pd.Series(predictions_fix)[list(pd.Series(y_test.tolist()).loc[lambda x : x == i].index)].value_counts())
    print('\n')

0
0     5992
2     4789
11    4397
27    3306
6     3096
16    2091
4     1523
95    1512
12    1400
8      233
20     138
13     105
40      84
1       19
5       11
10       3
dtype: int64


1
1     4831
16    3093
13    2774
20    2027
5     1901
12    1690
14    1556
8     1353
11     967
10     238
27     163
2       84
95      84
0       74
40      35
6       25
4        1
dtype: int64


3
40    2902
2     1260
10     781
4      371
8      251
11     211
16     135
6       47
95      31
5       26
12       8
14       4
13       1
dtype: int64


4
4     1718
95    1081
11     500
10     496
40     427
2      194
16      84
6       49
27      37
5       14
8        7
14       5
dtype: int64


25
14    1560
5      763
10     598
16      32
95      29
40      12
11       4
1        3
20       1
8        1
dtype: int64


7
16    1477
20     797
1      251
12     145
11     125
2       50
0       39
5       30
13      24
8        8
6        8
27       2
40       2
10       1
dtype: int

# Somoclu

In [17]:
import somoclu

In [40]:
# x=[]
# for index, row in X.iterrows():
#     x.append(row.values)

# print(x)
# sequence = tuple([X[item].values.T for item in X])
# print(sequence)
X_somoclu = np.float32(X.to_numpy())
print(X_somoclu)

[[4. 1. 5. ... 3. 4. 5.]
 [3. 5. 3. ... 2. 5. 3.]
 [2. 3. 4. ... 3. 4. 4.]
 ...
 [2. 2. 4. ... 5. 5. 2.]
 [3. 1. 5. ... 5. 5. 5.]
 [3. 4. 3. ... 5. 4. 5.]]


In [ ]:
som2 = somoclu.Somoclu(5, 4, maptype="planar",
                      gridtype="rectangular")
som2.train(X_somoclu, epochs=1000000)


In [ ]:
som2.view_umatrix(bestmatches=True, bestmatchcolors=colors, labels=labels)